# Generated by Django 4.2.5 on 2023-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2000-11-8 12:34'),
            preserve_default=False,
        ),
    ]
