# Generated by Django 4.2.5 on 2023-11-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hostel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_number',
            new_name='room_type',
        ),
    ]
