# Generated by Django 4.2.5 on 2023-11-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='hostel',
        ),
        migrations.AddField(
            model_name='hostel',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.services'),
            preserve_default=False,
        ),
    ]
