# Generated by Django 4.2.5 on 2023-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_rooms_picture_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='services',
            field=models.ManyToManyField(to='core.services', verbose_name='room_Services'),
        ),
    ]
