# Generated by Django 4.2.5 on 2023-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rooms_picture_alter_rooms_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('For Boys', 'First choice'), ('For Girls ', 'Second choice'), ('Both for Boys and Girls', 'Third choice')], default='For Boys', max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Two Seated', 'First choice'), ('Three Seated ', 'Second choice'), ('Five Seated', 'Third choice'), ('Five Seated', 'Third choice')], default='Two Seated', max_length=30),
        ),
    ]
