# Generated by Django 4.2.5 on 2023-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hostel_hostel_type_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('For Boys', 'For Boys'), ('For Girls ', 'For Girls '), ('Both for Boys and Girls', 'Both for Boys and Girls')], default='For Boys', max_length=50),
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='services',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Two Seated', 'Two Seated'), ('Three Seated ', 'Three Seated '), ('Five Seated', 'Four Seated'), ('Five Seated', 'Five Seated')], default='Two Seated', max_length=30),
        ),
        migrations.AddField(
            model_name='hostel',
            name='services',
            field=models.TextField(blank=True),
        ),
    ]
