# Generated by Django 4.2.5 on 2023-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_hostel_hostel_type_remove_hostel_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.CharField(default='1st', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='services',
        ),
        migrations.AddField(
            model_name='rooms',
            name='services',
            field=models.TextField(blank=True),
        ),
    ]
