# Generated by Django 4.2.5 on 2023-12-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rooms_floor_remove_rooms_services_rooms_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
