# Generated by Django 4.2.5 on 2023-12-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Two Seated', 'Two Seated'), ('Three Seated ', 'Three Seated '), ('Four Seated', 'Four Seated'), ('Five Seated', 'Five Seated')], default='Two Seated', max_length=30),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
