# Generated by Django 4.2.5 on 2023-12-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_feedback_hostel_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='embedCode',
            field=models.TextField(null=True),
        ),
    ]
