# Generated by Django 4.2.5 on 2023-12-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rooms_floor_remove_rooms_services_rooms_services'),
        ('booking', '0002_rename_check_in_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rooms'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_info',
            field=models.TextField(default='aasd'),
            preserve_default=False,
        ),
    ]
