# Generated by Django 4.2.5 on 2023-12-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booking_date_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_info',
            new_name='description',
        ),
    ]
