# Generated by Django 4.2.5 on 2023-12-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_room_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(),
        ),
    ]
