# Generated by Django 4.2.5 on 2023-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cnic',
            field=models.CharField(default='2472631283612', max_length=15),
            preserve_default=False,
        ),
    ]
