# Generated by Django 4.2.5 on 2023-10-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('hostel_admin', 'Hostel Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
