# Generated by Django 4.2.5 on 2023-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_hosteladmin_student_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteladmin',
            name='Hostel_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
