# Generated by Django 4.2.5 on 2023-10-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_university_location'),
        ('User', '0004_hosteladmin_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
    ]
