# Generated by Django 4.2.5 on 2023-10-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_university_location'),
        ('User', '0005_alter_student_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteladmin',
            name='university_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
    ]
