# Generated by Django 4.2.5 on 2023-10-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_hosteladmin_university_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteladmin',
            name='Hostel_name',
        ),
        migrations.RemoveField(
            model_name='hosteladmin',
            name='university_name',
        ),
    ]
