# Generated by Django 4.2.5 on 2023-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_hosteladmin_hostel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteladmin',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
