# Generated by Django 4.2.5 on 2023-11-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='student',
        ),
    ]
